---
# tasks file for EndPointProtection checks
- hosts: test
  vars_files: 
    - ../vars/userlist.yml
  tasks:
      - name: Add in all the users
        user:
         name: "{{ item }}"
         state: present
        with_items: "{{ user_name }}"        